from .pacote import PacoteSerializer,PacoteListSerializer,PacoteDetaiSerializer
from .cliente import ClienteSerializer, ClienteListSerializer, ClienteDetailSerializer
from .pacoteprocesso import PacotesProcessoSerializer
from .procedimento import  ParocedimentoSerializer, ProcedimentoListSerializer, ProcedimentoDetaiSerializer
from .agendamento import AgendamentoSerializer