# Generated by Django 4.2.5 on 2023-09-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("estetica", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedimento",
            name="imagem",
            field=models.ManyToManyField(related_name="+", to="uploader.image"),
        ),
    ]
